spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    cn.blue.mall: debug
    cn.blue.mall.demo.service.FeignAdminService: debug