spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345zxc
  data:
    mongodb:
      host: 192.168.2.135
      port: 27017
      database: userprod
  redis:
    host: 192.168.2.223 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
  rabbitmq:
    host: 192.168.2.223
    port: 5672
    virtual-host: vian
    username: admin
    password: admin
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
# 日志配置
logging:
  level:
    org.springframework.data.mongodb.core: debug
    cn.blue.mall.mapper: debug
    cn.blue.mall.portal.dao: debug