spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345zxc
  data:
    elasticsearch:
      cluster-nodes: 192.168.2.211:9301
      cluster-name: shuaiche-es
  elasticsearch:
    rest:
      uris: http://192.168.2.211:9201
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    cn.blue.mall: debug